@extends('frontend/master')

@section('maincontent')
    
    <!-- Enar-page-banner ____________________________ -->
    <div class="Enar-page-banner">
        <div class="Enar-page-banner-opact">
            <div class="container">
                <div>
                    <h1>Company Story</h1>
                    <ul>
                        <li><span></span></li>
                        <li><a href="{!! route('index') !!}">Home</a></li>
                        <li>/</li>
                        <li><a href="{!! route('about') !!}">About us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- /.Enar-page-banner -->
    <!-- About us ____________________________ -->
    <section class="About-us-section">
        <div class="container">
            <div class="row About-us-img-section">
                <div class="col-md-6 col-xs-12 ">
                    <div class="About-us-img">
                        <img src="{{ URL::asset('assets/images/frontend/about-us/img-1.jpg')}}" alt="image">
                    </div>
                </div>
                <div class="col-md-6 col-xs-12 img-text-border">
                    <div class="About-us-img-text">
                        <h3>Expereince the best<br>consultancy with us you<br>get never before</h3>
                        <span></span>
                        <p>EDIFYCONS IS THE BIG DATA AND CLOUD COMPUTING FOCUSED SPIN-OFF OF THE IT CONSULTANCY COMPANY CEDIANT. WE HELP OUR
                        CUSTOMERS TO STAY AFLOAT IN A COMPETITIVE MARKET WHERE THE KEY IS EFFICIENTLY CONVERTING DATA INTO KNOWLEDGE.</p>
                        <ul>
                            <li><img src="{{ URL::asset('assets/images/frontend/Them-logo/signatur-1.png')}}" alt="signatur"></li>
                            <li>
                                <h6><a href="#">Mohammed Khasim</a></h6>
                            </li>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
            </div>
    
            <div class="row About-us-text-section">
                <div class="col-md-6 col-xs-12">
                    <div class="About-us-text">
                        <h3>Our Story</h3>
                        <p>We are one of the world’s leading certification training providers.</p>
    
                        <p>We provide online training in disciplines such as Cyber Security, Cloud Computing, Project Management, Digital Marketing, and Data Science among others, where technologies and best practices are changing rapidly and demand for qualified candidates significantly exceeds supply.</p>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="About-us-text">
                        <h3>Our Mission</h3>
                        <p>It has been estimated that in the year 2020 the volume of data generated by humankind will amount to fifty times what
                        has been generated so far. The variety of data sources will also increase by a factor of seventy-five (IDC 2011). Data
                        are already a real asset for human wealth and progress.</p>
    
                        <p>At Edifycons, we transform Big Data opportunities into reality by offering analytics services that will help our
                        customers make better business decisions. We want to exceed our customers’ expectations with our knowledge, passion,
                        commitment, and our ability to provide solutions that, without reinventing the wheel, be the most innovative and use the
                        best tools in the industry.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Numver Section ____________________________ -->
    <section class="numver-section">
        <div class="numver-section-opact">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 col-xs-12">
                        <div class="numver-title">
                            <h2>Company<br>Facts in Number</h2>
                        </div>
                    </div>
                    <div class="col-sm-8 col-xs-12">
                        <div class="numver-item clear-fix">
                            <div>
                                <h2><span class="timer" data-from="0" data-to="5237" data-speed="2000"
                                        data-refresh-interval="5">0</span></h2>
                                <p>Proud Customers</p>
                            </div>
                            <div class="M-Exp-itam">
                                <h2><span class="timer" data-from="0" data-to="120" data-speed="2000"
                                        data-refresh-interval="5">0</span></h2>
                                <p>Expert Advisor</p>
                            </div>
                            <div>
                                <h2>
                                    <span class="timer" data-from="0" data-to="367" data-speed="2000"
                                        data-refresh-interval="5">0</span>
                                </h2>
                                <p>Completed Projects</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Home-two Experts section ____________________________ -->
    <section class="home-two-experts-section">
        <div class="container">
            <div class="them-main-title text-center">
                <h2>Meet Our Experts</h2>
                <span></span>
                <p>We have expert team member ready to solve your problem with fast delivery</p>
            </div>
    
            <div class="experts-claider-wrapper">
                <div id="home-two-experts-carousel" class="owl-carousel owl-theme">
                    <div class="item text-center">
                        <div>
                            <div class="expert-img"><img src="{{ URL::asset('assets/images/frontend/home/img-15.jpg')}}" alt="image"></div>
                            <h5><a href="team.html">Jeson Mark</a></h5>
                            <span>Senior Financial Officer</span>
                            <p>Jannatul fa is senior financial adviso and<br>working with us over 20 years.</p>
                        </div>
                    </div> <!-- / .Item -->
                    <div class="item text-center">
                        <div>
                            <div class="expert-img"><img src="{{ URL::asset('assets/images/frontend/home/img-16.jpg')}}" alt="image"></div>
                            <h5><a href="team.html">Jannatul Fa.</a></h5>
                            <span>Sells & Marketing Expert</span>
                            <p>Jannatul fa is senior financial adviso and<br>working with us over 20 years.</p>
                        </div>
                    </div> <!-- / .Item -->
                    <div class="item text-center">
                        <div>
                            <div class="expert-img"><img src="{{ URL::asset('assets/images/frontend/home/img-17.jpg')}}" alt="image"></div>
                            <h5><a href="team.html">Rashed Kabir</a></h5>
                            <span>Design & Devevlopment Expert</span>
                            <p>Jannatul fa is senior financial adviso and<br>working with us over 20 years.</p>
                        </div>
                    </div> <!-- / .Item -->
                    <div class="item text-center">
                        <div>
                            <div class="expert-img"><img src="{{ URL::asset('assets/images/frontend/home/img-16.jpg')}}" alt="image"></div>
                            <h5><a href="team.html">Jannatul Fa.</a></h5>
                            <span>Sells & Marketing Expert</span>
                            <p>Jannatul fa is senior financial adviso and<br>working with us over 20 years.</p>
                        </div>
                    </div> <!-- / .Item -->
                </div>
            </div>
        </div>
    </section>
    
    <!-- Choose Section ____________________________ -->
    <section class="choose-section clear-fix">
        <div class="left-side float-left">
            <div class="left-side-opact clear-fix">
                <div class="left-side-content float-right">
                    <div class="left-content-text">
                        <div class="them-main-title">
                            <h2>We Have<br>Many Reason to<br>Choose us</h2>
                            <span></span>
                        </div>
                        <p>You will not wrong to take our services as your business tool</p>
                        <a href="#" class="hvr-bounce-to-right">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="right-side float-right home-two-right-side">
            <div class="clear-fix">
                <div class="right-side-content float-left">
                    <div class="right-content-text clear-fix">
                        <div class="right-side-item">
                            <i class="flaticon flaticon-user"></i>
                            <h4><a href="#">Expert Coach Trainer</a></h4>
                            <p>Our coaches have the highest certifications in different personal development aspects and
                                years of experience coaching
                                businesses and individuals. They will mentor you and provide the guidance and support you
                                need so you can rise above
                                challenges and achieve your personal goals, in love and relationship, career or any aspect
                                of life you choose. Read
                                expert profiles and find the coach for you.</p>
                        </div>
                        <div class="right-side-item">
                            <i class="flaticon flaticon-umbrella"></i>
                            <h4><a href="#">Trsuted Vendor</a></h4>
                            <p>PMI, the Registered Education Provider logo, PMBOK, PMP, PgMP, CAPM,PMI-RMP, PMI-ACP, the PMI
                                logo, and the PMP logo are
                                marks of the Project Management Institute, Inc.ITIL, PRINCE2, and MSP are registered
                                trademarks of AXELOS Limited, used under permission of AXELOS Limited. All rights
                                reserved."The Swirl logo™ is a trade mark of AXELOS Limited, used under permission of AXELOS
                                Limited. All rights reserved.</p>
                        </div>
                        {{-- <div class="right-side-item">
                            <i class="flaticon flaticon-medal"></i>
                            <h4><a href="#">Award Winner</a></h4>
                            <p>Lorem ipsum dolor sit amet, dolor pr.Percipit imper brute nulla novumo amet dolo.</p>
                        </div> --}}
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Home Client Claider ____________________________ -->
    <section class="home-client-claider">
        <div class="container">
            <div class="them-main-title text-center">
                <h2>What Client Say</h2>
                <span></span>
            </div>
            <div class="client-claider-wrapper">
                <div id="client-claider-carousel" class="owl-carousel owl-theme">
                    <div class="item">
                        <div>
                            <p>With my digital marketing master course from Edifycons, I was awarded a job as Digital
                                Marketing Manager for a leading
                                Advertising Agency. Due to my unparallel knowledge in DM, there is also a contractually
                                binding agreement for Equity
                                Stake. All thanks to Edifycons.</p>
                            <div>
                                <span></span>
                                <img src="{{ URL::asset('assets/images/frontend/Them-logo/icon-6.png') }}" alt="logo">
                                <h6><a href="#">Mohasin Khan</a></h6>
                                {{-- <i>Co-Founder of UnifyTheme</i> --}}
                            </div>
                        </div>
                    </div>
                    <!-- / .Item -->
                    <div class="item">
                        <div>
                            <p>The skills gained from the certification helped me to optimize my clients' website and
                                measure the outcome of my
                                decisions on a website.</p>
                            <div>
                                <span></span>
                                <img src="{{ URL::asset('assets/images/frontend/Them-logo/icon-6.png') }}" alt="logo">
                                <h6><a href="#">Shivani Vannan</a></h6>
                                {{-- <i>Co-Founder of UnifyTheme</i> --}}
                            </div>
                        </div>
                    </div>
                    <!-- / .Item -->
                    <div class="item">
                        <div>
                            <p>My trainer was really very patient and made sure to address all our doubts. The journey with
                                Edifycons has indeed been a
                                great experience because of the way the trainers explained the topics.</p>
                            <div>
                                <span></span>
                                <img src="{{ URL::asset('assets/images/frontend/Them-logo/icon-6.png') }}" alt="logo">
                                <h6><a href="#">Ang Qiao Ni Shemin</a></h6>
                                {{-- <i>Co-Founder of UnifyTheme</i> --}}
                            </div>
                        </div>
                    </div>
                    <!-- / .Item -->
                    <div class="item">
                        <div>
                            <p>It was a nice learning experience so far, specially class assignment and recorded classroom
                                videos help me a lot in
                                practicing and understanding the concept better. Old instructor's videos also helped a lot
                                in adding some more knowledge
                                what i gained in live session. Would also like to thank Edifycons support team for their
                                great support over emails to
                                get clarify the issues I had.</p>
                            <div>
                                <span></span>
                                <img src="{{ URL::asset('assets/images/frontend/Them-logo/icon-6.png') }}" alt="logo">
                                <h6><a href="#">Goh Yi Chong</a></h6>
                                {{-- <i>Co-Founder of UnifyTheme</i> --}}
                            </div>
                        </div>
                    </div>
                    <!-- / .Item -->
                </div>
            </div>
            <!-- / .Home Client Claider -->
        </div>
    </section>
    
    <!-- home Logo Slide ____________________________ -->
    <section class="home-logo-slide">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-xs-12">
                    <div class="them-main-title">
                        <h2>Who<br>Behind us</h2>
                        <span></span>
                    </div>
                </div>
                <div class="col-md-8 col-xs-12">
                    <div class="logo-claider-wrapper">
                        <div id="logo-claider-carousel" class="owl-carousel owl-theme">
                           <div class="item">
                            <div>
                                <img src="{{ URL::asset('assets/images/frontend/home/pennstate.jpg')}}"  style="    height: 260px;" alt="logo">
                            </div>
                        </div>
                        <!-- / .Item -->
                        <div class="item">
                            <div>
                                <img src="{{ URL::asset('assets/images/frontend/home/usf.jpg')}}" style="    height: 260px;" alt="logo">
                            </div>
                        </div>
                        <!-- / .Item -->
                        <div class="item">
                            <div>
                                <img src="{{ URL::asset('assets/images/frontend/home/strayer.jpg')}}" style="    height: 260px;" alt="logo">
                            </div>
                        </div>
                        <!-- / .Item -->
                        <div class="item">
                            <div>
                                <img src="{{ URL::asset('assets/images/frontend/home/rutgers.jpg')}}" style="    height: 260px;" alt="logo">
                            </div>
                        </div>
                        <!-- / .Item -->
                        </div>
                    </div> <!-- / .logo-claider-wrapper -->
                </div>
            </div>
        </div>
    </section>

@stop

@section('custom-footer-scripts')
@stop


    



   